In [422]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

### Import and preprocess data from csv

In [423]:
raw_df = pd.read_csv("data.csv")
raw_df.head()

,Unnamed: 0,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,...,grew,hurt,changed,bleed,elevation,img_id,biopsed,compactness,avg_hue,asymetry
0,43,PAT_621,1183,False,False,UNK,UNK,34,False,MALE,...,UNK,False,UNK,False,False,PAT_621_1183_56.png,True,3.887952,0.065314,0.105118
1,53,PAT_680,1289,True,False,PORTUGAL,ITALY,78,False,MALE,...,True,False,True,False,True,PAT_680_1289_182.png,True,1.806027,0.024714,0.182668
2,58,PAT_333,1469,False,False,ITALY,GERMANY,51,False,FEMALE,...,True,False,True,False,False,PAT_333_1469_499.png,True,0.968168,0.140772,0.104714
3,65,PAT_544,3299,False,False,NaN,NaN,87,False,FEMALE,...,True,False,False,False,True,PAT_544_3299_671.png,False,2.990376,0.018016,0.349029
4,73,PAT_701,4056,False,True,POMERANIA,POMERANIA,69,False,MALE,...,False,False,False,False,True,PAT_701_4056_457.png,False,5.196122,0.015243,0.294738

In [424]:
COI = ["diagnostic", "age", "itch", "grew", "hurt", "changed", "bleed", "elevation", "compactness","asymetry"] # "avg_red_channel", "avg_blue_channel", "avg_green_channel"]
df = raw_df.loc[:,COI]
df = df.dropna()

In [425]:
COIbool = ["itch", "grew", "hurt", "changed", "bleed", "elevation"]
d = {"False": 0, "True": 1, False: 0, True:1, "UNK": None}
for col in COIbool:
    df[col] = df[col].replace(d)
df = df.dropna()
df

,diagnostic,age,itch,grew,hurt,changed,bleed,elevation,compactness,asymetry
1,MEL,78,0,1.0,0.0,1.0,0,1.0,1.806027,0.182668
2,NEV,51,0,1.0,0.0,1.0,0,0.0,0.968168,0.104714
3,SEK,87,0,1.0,0.0,0.0,0,1.0,2.990376,0.349029
4,SEK,69,0,0.0,0.0,0.0,0,1.0,5.196122,0.294738
7,SEK,90,0,1.0,0.0,0.0,0,1.0,1.762241,0.103679
...,...,...,...,...,...,...,...,...,...,...
93,MEL,70,0,1.0,0.0,1.0,0,0.0,4.902733,1.930779
95,SEK,73,1,1.0,0.0,0.0,0,1.0,0.769074,0.352734
96,NEV,14,0,0.0,0.0,0.0,0,0.0,4.505586,0.077976
97,NEV,32,1,1.0,0.0,1.0,0,0.0,0.276632,0.795556
99,BCC,73,1,1.0,1.0,0.0,1,0.0,2.894087,0.202768

In [426]:
y = df["diagnostic"]
X = df.drop("diagnostic",axis=1)

In [427]:
cancers = {"BCC":1, "MEL":1, "SCC": 1, "ACK": 0, "NEV":0, "SEK":0}
y = y.replace(cancers)

In [428]:
# diagnostics = {"BCC":0, "MEL":1, "SCC": 2, "ACK": 3, "NEV":4, "SEK":5}
# y = y.replace(diagnostics)

In [429]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X_norm = scalar.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_norm, y,test_size=0.25, train_size=0.75)

In [430]:
clf  = LogisticRegression().fit(X = X_train, y = y_train)

pred = clf.predict(X_test)
print(clf.score(X_test, y_test))

print(y_train)

0.6111111111111112
20    0
59    1
18    1
41    1
25    0
31    1
62    1
34    0
44    1
93    1
48    1
73    1
16    0
15    1
90    1
33    0
74    0
52    1
1     1
88    1
9     1
45    1
89    0
87    0
13    0
36    0
53    1
64    0
23    1
10    1
95    0
66    1
55    0
97    0
4     0
12    1
85    0
46    0
63    1
58    1
21    0
92    1
78    1
80    0
2     0
77    1
81    1
76    1
71    1
51    1
35    1
83    0
Name: diagnostic, dtype: int64